power_sensors:
  washing_machine:
    entity_id: sensor.washing_machine_power
    channel_type: consumer
    min_power_w: 0
    max_power_w: 2500
    max_age_seconds: 30

estimated_consumers:
  tv:
    entity_id: switch.tv
    estimated_power_w: 85
    max_age_seconds: 60

constant_consumers:
  fridge:
    estimated_power_w: 50

outputs:
  estimated_total_load:
    entity_id: sensor.residential_estimated_total_load

  battery_soc:
    entity_id: sensor.residential_battery_soc

  battery_input_power:
    entity_id: sensor.residential_battery_input_power

  battery_output_power:
    entity_id: sensor.residential_battery_output_power

  battery_output_target:
    entity_id: sensor.residential_battery_output_target

battery:
  capacity_wh: 2500
  min_soc_percent: 20
  max_output_power_w: 800
  max_age_seconds: 120